name: openapi-diff
on:
  pull_request:
    paths:
      - 'api-docs/**'

jobs:
  check-diff:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8.12]
    steps:
      - name: Checkout getsentry/sentry
        uses: actions/checkout@v2
        with:
          path: sentry

      - name: Setup sentry env (python ${{ matrix.python-version }})
        uses: ./sentry/.github/actions/setup-sentry
        with:
          python-version: ${{ matrix.python-version }}
          # Note this uses a different cache key than other backend-based workflows because this workflows dependencies are different
          cache-files-hash: ${{ hashFiles('requirements-pre-commit.txt') }}

      - name: Getsentry Token
        id: getsentry
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - name: Checkout getsentry/sentry-api-schema
        uses: actions/checkout@v2
        with:
          ref: 'main'
          repository: getsentry/sentry-api-schema
          path: sentry-api-schema
          token: ${{ steps.getsentry.outputs.token }}

      - name: Install/setup node
        uses: volta-cli/action@v1

      - name: Build OpenAPI Derefed JSON
        run: |
          cd sentry
          yarn install --frozen-lockfile
          yarn run build-derefed-docs api-docs/openapi-derefed.json

      - name: Compare OpenAPI Derefed JSON
        run: |
          npx json-diff --color sentry-api-schema/openapi-derefed.json sentry/api-docs/openapi-derefed.json
